# Generated by Django 5.0.4 on 2024-04-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('carbohydrates_total_g', models.FloatField()),
                ('fat_total_g', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('sodium_mg', models.FloatField()),
                ('sugar_g', models.FloatField()),
            ],
        ),
    ]
